/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    tags: Tag;
    series: Series;
    posts: Post;
    media: Media;
    projects: Project;
    'work-experience': WorkExperience;
    favorites: Favorite;
    books: Book;
    'reading-notes': ReadingNote;
    'habit-completions': HabitCompletion;
    'error-logs': ErrorLog;
    streaks: Streak;
    notebooks: Notebook;
    documents: Document;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    series: SeriesSelect<false> | SeriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'work-experience': WorkExperienceSelect<false> | WorkExperienceSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    'reading-notes': ReadingNotesSelect<false> | ReadingNotesSelect<true>;
    'habit-completions': HabitCompletionsSelect<false> | HabitCompletionsSelect<true>;
    'error-logs': ErrorLogsSelect<false> | ErrorLogsSelect<true>;
    streaks: StreaksSelect<false> | StreaksSelect<true>;
    notebooks: NotebooksSelect<false> | NotebooksSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role?: ('admin' | 'author') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  slug: string;
  /**
   * Optional. Shown on the tag index page.
   */
  description?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  parsedContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series".
 */
export interface Series {
  id: number;
  name: string;
  slug: string;
  /**
   * Shown at the top of each post in the series.
   */
  description?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Used in the post URL.
   */
  slug: string;
  /**
   * 1–2 sentence summary. Used for SEO meta, card previews, and the TTS audio intro.
   */
  description?: string | null;
  coverImage?: (number | null) | Media;
  status?: ('draft' | 'published' | 'archived') | null;
  publishedAt?: string | null;
  /**
   * Auto-computed on save. Estimated reading time in minutes.
   */
  readingTime?: number | null;
  /**
   * Auto-computed on save. Word count of post content.
   */
  wordCount?: number | null;
  /**
   * Auto-extracted heading structure for Table of Contents. Array of { id, text, level }.
   */
  tocItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  tags?: (number | Tag)[] | null;
  series?: (number | null) | Series;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  audio_summary?: (number | null) | Media;
  /**
   * Timestamp of the last TTS generation.
   */
  audio_generated_at?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Screen reader description. Required for images.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Photographer or source credit.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  title?: string | null;
  description: string;
  url: string;
  status?: ('active' | 'wip' | 'archived') | null;
  year?: string | null;
  tech?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  github?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experience".
 */
export interface WorkExperience {
  id: number;
  company: string;
  role: string;
  date_range?: string | null;
  logo?: (number | null) | Media;
  tech_stack?: string | null;
  bullets?:
    | {
        label: string;
        href?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  type?: ('article' | 'video' | 'podcast' | 'book' | 'tool') | null;
  title: string;
  url?: string | null;
  thumbnailUrl?: string | null;
  source?: string | null;
  thoughts?: string | null;
  dateAdded: string;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  title: string;
  author?: string | null;
  totalPages?: number | null;
  currentPage: number;
  status: 'reading' | 'completed' | 'paused' | 'wishlist';
  coverImage?: (number | null) | Media;
  startedAt?: string | null;
  finishedAt?: string | null;
  summary?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-notes".
 */
export interface ReadingNote {
  id: number;
  book: number | Book;
  /**
   * YYYY-MM-DD
   */
  date: string;
  pageStart: number;
  pageEnd: number;
  /**
   * Auto-computed from page range.
   */
  pagesRead: number;
  thoughts?: string | null;
  habitCompletion?: (number | null) | HabitCompletion;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habit-completions".
 */
export interface HabitCompletion {
  id: number;
  habitKey: 'reading' | 'workout' | 'steps' | 'eating' | 'sleep' | 'coding' | 'editing';
  /**
   * YYYY-MM-DD
   */
  date: string;
  completed: boolean;
  /**
   * Numeric progress for the day (pages, steps, score, etc.).
   */
  value?: number | null;
  notes?: string | null;
  readingNote?: (number | null) | ReadingNote;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs".
 */
export interface ErrorLog {
  id: number;
  level: 'info' | 'warn' | 'error' | 'fatal';
  source: string;
  message: string;
  stack?: string | null;
  /**
   * Additional structured context (route, payload, user agent, etc.).
   */
  context?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  occurredAt: string;
  resolved?: boolean | null;
  resolvedAt?: string | null;
  resolutionNotes?: string | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks".
 */
export interface Streak {
  id: number;
  label: string;
  date: string;
  completed?: boolean | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notebooks".
 */
export interface Notebook {
  id: number;
  /**
   * YYYY-MM-DD
   */
  date: string;
  visibility: 'public' | 'private';
  pinned?: boolean | null;
  /**
   * Note blocks for this day
   */
  blocks?:
    | {
        /**
         * Optional. Auto-generated if left blank (for permalinks).
         */
        blockId?: string | null;
        type: 'thought' | 'code' | 'link' | 'learning' | 'quote' | 'bugs' | 'features' | 'reminders' | 'work';
        content: string;
        lang?: string | null;
        meta?: string | null;
        /**
         * Array of tag strings
         */
        tags?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Paste raw Markdown here and save — it will be auto-converted into the Content field below.
   */
  markdownInput?: string | null;
  /**
   * Auto-populated from the Markdown above, or edit directly.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Server-rendered HTML for use in your frontend.
   */
  contentHtml?: string | null;
  /**
   * Or choose an existing Markdown document to use its content.
   */
  sourceDocument?: (number | null) | Document;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'series';
        value: number | Series;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'work-experience';
        value: number | WorkExperience;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'reading-notes';
        value: number | ReadingNote;
      } | null)
    | ({
        relationTo: 'habit-completions';
        value: number | HabitCompletion;
      } | null)
    | ({
        relationTo: 'error-logs';
        value: number | ErrorLog;
      } | null)
    | ({
        relationTo: 'streaks';
        value: number | Streak;
      } | null)
    | ({
        relationTo: 'notebooks';
        value: number | Notebook;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "series_select".
 */
export interface SeriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  coverImage?: T;
  status?: T;
  publishedAt?: T;
  readingTime?: T;
  wordCount?: T;
  tocItems?: T;
  tags?: T;
  series?: T;
  content?: T;
  audio_summary?: T;
  audio_generated_at?: T;
  markdownInput?: T;
  contentHtml?: T;
  sourceDocument?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  description?: T;
  url?: T;
  status?: T;
  year?: T;
  tech?:
    | T
    | {
        label?: T;
        id?: T;
      };
  github?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-experience_select".
 */
export interface WorkExperienceSelect<T extends boolean = true> {
  company?: T;
  role?: T;
  date_range?: T;
  logo?: T;
  tech_stack?: T;
  bullets?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  type?: T;
  title?: T;
  url?: T;
  thumbnailUrl?: T;
  source?: T;
  thoughts?: T;
  dateAdded?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  title?: T;
  author?: T;
  totalPages?: T;
  currentPage?: T;
  status?: T;
  coverImage?: T;
  startedAt?: T;
  finishedAt?: T;
  summary?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reading-notes_select".
 */
export interface ReadingNotesSelect<T extends boolean = true> {
  book?: T;
  date?: T;
  pageStart?: T;
  pageEnd?: T;
  pagesRead?: T;
  thoughts?: T;
  habitCompletion?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "habit-completions_select".
 */
export interface HabitCompletionsSelect<T extends boolean = true> {
  habitKey?: T;
  date?: T;
  completed?: T;
  value?: T;
  notes?: T;
  readingNote?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "error-logs_select".
 */
export interface ErrorLogsSelect<T extends boolean = true> {
  level?: T;
  source?: T;
  message?: T;
  stack?: T;
  context?: T;
  occurredAt?: T;
  resolved?: T;
  resolvedAt?: T;
  resolutionNotes?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "streaks_select".
 */
export interface StreaksSelect<T extends boolean = true> {
  label?: T;
  date?: T;
  completed?: T;
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notebooks_select".
 */
export interface NotebooksSelect<T extends boolean = true> {
  date?: T;
  visibility?: T;
  pinned?: T;
  blocks?:
    | T
    | {
        blockId?: T;
        type?: T;
        content?: T;
        lang?: T;
        meta?: T;
        tags?: T;
        id?: T;
      };
  markdownInput?: T;
  content?: T;
  contentHtml?: T;
  sourceDocument?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  parsedContent?: T;
  contentHtml?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  name: string;
  tagline?: string | null;
  bio?: string | null;
  available_for_work?: boolean | null;
  github?: string | null;
  x?: string | null;
  linkedin?: string | null;
  email?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  tagline?: T;
  bio?: T;
  available_for_work?: T;
  github?: T;
  x?: T;
  linkedin?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}